Repository ds-wizard/engine-backend, pull requests merged in 2020-11, with the labels that each got.

#42 Release 2.8.0 (develop)
  engine-registry/package.yaml
  engine-shared/package.yaml
  engine-wizard-metamodel-migrator/package.yaml
  engine-wizard/package.yaml
Labels: release

#46 [DSW-979] Clear default template after project migration
  engine-wizard/src/Wizard/Service/Migration/Questionnaire/MigratorService.hs
Labels: bugfix

#47 [DSW-981] Fix move question in questionnaire migration
  engine-shared/src/Shared/Model/Questionnaire/QuestionnaireUtil.hs
  engine-wizard/src/Wizard/Service/Migration/Questionnaire/Migrator/MoveSanitizator.hs
  engine-wizard/test/Wizard/Specs/Service/Migration/Questionnaire/MoveSanitizatorSpec.hs
Labels: bugfix

#48 Hotfix 2.8.1
  engine-registry/package.yaml
  engine-shared/package.yaml
  engine-shared/src/Shared/Model/Questionnaire/QuestionnaireUtil.hs
  engine-wizard-metamodel-migrator/package.yaml
  engine-wizard/package.yaml
  engine-wizard/src/Wizard/Service/Migration/Questionnaire/Migrator/MoveSanitizator.hs
  engine-wizard/src/Wizard/Service/Migration/Questionnaire/MigratorService.hs
  engine-wizard/src/Wizard/Service/Package/PackageMapper.hs
  engine-wizard/src/Wizard/Service/Template/TemplateMapper.hs
  engine-wizard/src/Wizard/Service/Template/TemplateService.hs
  engine-wizard/src/Wizard/Service/Template/TemplateUtil.hs
  engine-wizard/test/Wizard/Specs/Service/Migration/Questionnaire/MoveSanitizatorSpec.hs
Labels: hotfix

#49 Hotfix 2.8.1 (develop)
  engine-registry/package.yaml
  engine-shared/package.yaml
  engine-wizard-metamodel-migrator/package.yaml
  engine-wizard/package.yaml
Labels: hotfix
