Repository ds-wizard/engine-backend, pull requests merged in 2020-05, with the labels that each got.

#21 Release 2.3.0 (develop)
  engine-registry/package.yaml
  engine-shared/package.yaml
  engine-wizard-metamodel-migrator/package.yaml
  engine-wizard/package.yaml
Labels: release

#22 Hotfix 2.3.1
  engine-registry/package.yaml
  engine-shared/package.yaml
  engine-wizard-metamodel-migrator/package.yaml
  engine-wizard/package.yaml
  engine-wizard/src/Wizard/Api/Resource/User/UserDTO.hs
  engine-wizard/src/Wizard/Service/User/UserMapper.hs
Labels: hotfix

#24 [DSW-823] Use human-friendly document filenames
  engine-wizard/src/Wizard/Api/Handler/Document/Detail_Download_GET.hs
Labels: feature
